app = "hangman-game"

primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python -u run.py"

[http_service]
  internal_port = 8080
  force_http_to_https = false
  disable_http_checks = true